# Generated by Django 5.1.2 on 2024-11-04 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_sensordata_temperature_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='sensordata',
            name='accounts_se_timesta_adead9_idx',
        ),
        migrations.RemoveField(
            model_name='sensordata',
            name='temperature',
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='humidity_percent',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='sensor_value',
            field=models.IntegerField(),
        ),
    ]
